# Global output directory for symlink libraries.
# Symlink library subdirectories are created inside this path.
# Can be overridden per library.
output_path: /media/filtered

libraries:
  - name: "Movies"
    input_path: /media/movies
    # output_path: /media/filtered/movies  # optional per-library override
    symlink_libraries:
      - filters:
          - type: audio_language
            languages:
              - deu

  - name: "Shows"
    input_path: /media/shows
    symlink_libraries:
      - filters:
          - type: audio_language
            languages:
              - deu
