services:
  boomarr:
    build: .
    container_name: boomarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: "022"
      TZ: UTC
      LOG_LEVEL: debug
    volumes:
      - ./config-docker:/config
    command: boomarr watch
