services:
  boomarr:
    build: .
    container_name: boomarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK: "022"
      TZ: UTC
      LOG_LEVEL: debug
    volumes:
      - ./config-docker:/config
      - ./config-docker/output/filtered:/media/filtered
      - ./tests/fixtures/media/movies:/media/movies:ro
      - ./tests/fixtures/media/shows:/media/shows:ro
    ports:
      - "9797:9797"
