{{- if and .Values.webhook.enabled .Values.webhook.apiKey (not .Values.webhook.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boomarr.fullname" . }}
  labels:
    {{- include "boomarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webhook.existingSecretKey }}: {{ .Values.webhook.apiKey | quote }}
{{- end }}
