{{- $apiKey := and .Values.server.enabled .Values.server.apiKey (not .Values.server.existingSecret) }}
{{- if or $apiKey .Values.notifyUrls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boomarr.fullname" . }}
  labels:
    {{- include "boomarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $apiKey }}
  {{ .Values.server.existingSecretKey }}: {{ .Values.server.apiKey | quote }}
  {{- end }}
  {{- with .Values.notifyUrls }}
  notify-urls: {{ join " " . | quote }}
  {{- end }}
{{- end }}
