{{- $apiKey := and .Values.server.enabled .Values.server.apiKey (not .Values.server.existingSecret) }}
{{- $auth := and .Values.auth.username .Values.auth.password (not .Values.auth.existingSecret) }}
{{- if or $apiKey $auth .Values.notifyUrls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "boomarr.fullname" . }}
  labels:
    {{- include "boomarr.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $apiKey }}
  {{ .Values.server.existingSecretKey }}: {{ .Values.server.apiKey | quote }}
  {{- end }}
  {{- if $auth }}
  {{ .Values.auth.usernameKey }}: {{ .Values.auth.username | quote }}
  {{ .Values.auth.passwordKey }}: {{ .Values.auth.password | quote }}
  {{- end }}
  {{- with .Values.notifyUrls }}
  notify-urls: {{ join " " . | quote }}
  {{- end }}
{{- end }}
