"""ISO 639 language code normalisation.

Matroska stores audio languages as ISO 639-2/B codes (``ger``, ``fre``),
while many other containers and tools use ISO 639-2/T (``deu``, ``fra``) or
ISO 639-1 (``de``, ``fr``). :func:`normalize_language` folds all of these
onto the ISO 639-2/T form so that a single configured code matches every
spelling of the same language.

Data derived from the Debian ``iso-codes`` project (ISO 639-2 table).
"""

from typing import Final

ISO_639_1_TO_2T: Final[dict[str, str]] = {
    "aa": "aar",
    "ab": "abk",
    "ae": "ave",
    "af": "afr",
    "ak": "aka",
    "am": "amh",
    "an": "arg",
    "ar": "ara",
    "as": "asm",
    "av": "ava",
    "ay": "aym",
    "az": "aze",
    "ba": "bak",
    "be": "bel",
    "bg": "bul",
    "bh": "bih",
    "bi": "bis",
    "bm": "bam",
    "bn": "ben",
    "bo": "bod",
    "br": "bre",
    "bs": "bos",
    "ca": "cat",
    "ce": "che",
    "ch": "cha",
    "co": "cos",
    "cr": "cre",
    "cs": "ces",
    "cu": "chu",
    "cv": "chv",
    "cy": "cym",
    "da": "dan",
    "de": "deu",
    "dv": "div",
    "dz": "dzo",
    "ee": "ewe",
    "el": "ell",
    "en": "eng",
    "eo": "epo",
    "es": "spa",
    "et": "est",
    "eu": "eus",
    "fa": "fas",
    "ff": "ful",
    "fi": "fin",
    "fj": "fij",
    "fo": "fao",
    "fr": "fra",
    "fy": "fry",
    "ga": "gle",
    "gd": "gla",
    "gl": "glg",
    "gn": "grn",
    "gu": "guj",
    "gv": "glv",
    "ha": "hau",
    "he": "heb",
    "hi": "hin",
    "ho": "hmo",
    "hr": "hrv",
    "ht": "hat",
    "hu": "hun",
    "hy": "hye",
    "hz": "her",
    "ia": "ina",
    "id": "ind",
    "ie": "ile",
    "ig": "ibo",
    "ii": "iii",
    "ik": "ipk",
    "io": "ido",
    "is": "isl",
    "it": "ita",
    "iu": "iku",
    "ja": "jpn",
    "jv": "jav",
    "ka": "kat",
    "kg": "kon",
    "ki": "kik",
    "kj": "kua",
    "kk": "kaz",
    "kl": "kal",
    "km": "khm",
    "kn": "kan",
    "ko": "kor",
    "kr": "kau",
    "ks": "kas",
    "ku": "kur",
    "kv": "kom",
    "kw": "cor",
    "ky": "kir",
    "la": "lat",
    "lb": "ltz",
    "lg": "lug",
    "li": "lim",
    "ln": "lin",
    "lo": "lao",
    "lt": "lit",
    "lu": "lub",
    "lv": "lav",
    "mg": "mlg",
    "mh": "mah",
    "mi": "mri",
    "mk": "mkd",
    "ml": "mal",
    "mn": "mon",
    "mr": "mar",
    "ms": "msa",
    "mt": "mlt",
    "my": "mya",
    "na": "nau",
    "nb": "nob",
    "nd": "nde",
    "ne": "nep",
    "ng": "ndo",
    "nl": "nld",
    "nn": "nno",
    "no": "nor",
    "nr": "nbl",
    "nv": "nav",
    "ny": "nya",
    "oc": "oci",
    "oj": "oji",
    "om": "orm",
    "or": "ori",
    "os": "oss",
    "pa": "pan",
    "pi": "pli",
    "pl": "pol",
    "ps": "pus",
    "pt": "por",
    "qu": "que",
    "rm": "roh",
    "rn": "run",
    "ro": "ron",
    "ru": "rus",
    "rw": "kin",
    "sa": "san",
    "sc": "srd",
    "sd": "snd",
    "se": "sme",
    "sg": "sag",
    "si": "sin",
    "sk": "slk",
    "sl": "slv",
    "sm": "smo",
    "sn": "sna",
    "so": "som",
    "sq": "sqi",
    "sr": "srp",
    "ss": "ssw",
    "st": "sot",
    "su": "sun",
    "sv": "swe",
    "sw": "swa",
    "ta": "tam",
    "te": "tel",
    "tg": "tgk",
    "th": "tha",
    "ti": "tir",
    "tk": "tuk",
    "tl": "tgl",
    "tn": "tsn",
    "to": "ton",
    "tr": "tur",
    "ts": "tso",
    "tt": "tat",
    "tw": "twi",
    "ty": "tah",
    "ug": "uig",
    "uk": "ukr",
    "ur": "urd",
    "uz": "uzb",
    "ve": "ven",
    "vi": "vie",
    "vo": "vol",
    "wa": "wln",
    "wo": "wol",
    "xh": "xho",
    "yi": "yid",
    "yo": "yor",
    "za": "zha",
    "zh": "zho",
    "zu": "zul",
}

ISO_639_2B_TO_2T: Final[dict[str, str]] = {
    "alb": "sqi",
    "arm": "hye",
    "baq": "eus",
    "bur": "mya",
    "chi": "zho",
    "cze": "ces",
    "dut": "nld",
    "fre": "fra",
    "geo": "kat",
    "ger": "deu",
    "gre": "ell",
    "ice": "isl",
    "mac": "mkd",
    "mao": "mri",
    "may": "msa",
    "per": "fas",
    "rum": "ron",
    "slo": "slk",
    "tib": "bod",
    "wel": "cym",
}


# English language names (as reported e.g. by older Sonarr/Radarr versions).
ISO_639_NAMES: Final[dict[str, str]] = {
    "abkhazian": "abk",
    "achinese": "ace",
    "acoli": "ach",
    "adangme": "ada",
    "adygei": "ady",
    "adyghe": "ady",
    "afar": "aar",
    "afrihili": "afh",
    "afrikaans": "afr",
    "afro-asiatic languages": "afa",
    "ainu": "ain",
    "akan": "aka",
    "akkadian": "akk",
    "albanian": "sqi",
    "alemannic": "gsw",
    "aleut": "ale",
    "algonquian languages": "alg",
    "alsatian": "gsw",
    "altaic languages": "tut",
    "amharic": "amh",
    "angika": "anp",
    "apache languages": "apa",
    "arabic": "ara",
    "aragonese": "arg",
    "arapaho": "arp",
    "arawak": "arw",
    "armenian": "hye",
    "aromanian": "rup",
    "artificial languages": "art",
    "arumanian": "rup",
    "assamese": "asm",
    "asturian": "ast",
    "asturleonese": "ast",
    "athapascan languages": "ath",
    "australian languages": "aus",
    "austronesian languages": "map",
    "avaric": "ava",
    "avestan": "ave",
    "awadhi": "awa",
    "aymara": "aym",
    "azerbaijani": "aze",
    "bable": "ast",
    "balinese": "ban",
    "baltic languages": "bat",
    "baluchi": "bal",
    "bambara": "bam",
    "bamileke languages": "bai",
    "banda languages": "bad",
    "bantu (other)": "bnt",
    "basa": "bas",
    "bashkir": "bak",
    "basque": "eus",
    "batak languages": "btk",
    "bedawiyet": "bej",
    "beja": "bej",
    "belarusian": "bel",
    "bemba": "bem",
    "bengali": "ben",
    "berber languages": "ber",
    "bhojpuri": "bho",
    "bihari languages": "bih",
    "bikol": "bik",
    "bilin": "byn",
    "bini": "bin",
    "bislama": "bis",
    "blin": "byn",
    "bliss": "zbl",
    "blissymbolics": "zbl",
    "blissymbols": "zbl",
    "bokmål, norwegian": "nob",
    "bosnian": "bos",
    "braj": "bra",
    "breton": "bre",
    "buginese": "bug",
    "bulgarian": "bul",
    "buriat": "bua",
    "burmese": "mya",
    "caddo": "cad",
    "cantonese": "zho",
    "castilian": "spa",
    "catalan": "cat",
    "caucasian languages": "cau",
    "cebuano": "ceb",
    "celtic languages": "cel",
    "central american indian languages": "cai",
    "central khmer": "khm",
    "chagatai": "chg",
    "chamic languages": "cmc",
    "chamorro": "cha",
    "chechen": "che",
    "cherokee": "chr",
    "chewa": "nya",
    "cheyenne": "chy",
    "chibcha": "chb",
    "chichewa": "nya",
    "chinese": "zho",
    "chinese (simplified)": "zho",
    "chinese (traditional)": "zho",
    "chinook jargon": "chn",
    "chipewyan": "chp",
    "choctaw": "cho",
    "chuang": "zha",
    "church slavic": "chu",
    "church slavonic": "chu",
    "chuukese": "chk",
    "chuvash": "chv",
    "classical nepal bhasa": "nwc",
    "classical newari": "nwc",
    "classical syriac": "syc",
    "cook islands maori": "rar",
    "coptic": "cop",
    "cornish": "cor",
    "corsican": "cos",
    "cree": "cre",
    "creek": "mus",
    "creoles and pidgins": "crp",
    "creoles and pidgins, english based": "cpe",
    "creoles and pidgins, french-based": "cpf",
    "creoles and pidgins, portuguese-based": "cpp",
    "crimean tatar": "crh",
    "crimean turkish": "crh",
    "croatian": "hrv",
    "cushitic languages": "cus",
    "czech": "ces",
    "dakota": "dak",
    "danish": "dan",
    "dargwa": "dar",
    "delaware": "del",
    "dene suline": "chp",
    "dhivehi": "div",
    "dimili": "zza",
    "dimli": "zza",
    "dinka": "din",
    "divehi": "div",
    "dogri": "doi",
    "dogrib": "dgr",
    "dravidian languages": "dra",
    "duala": "dua",
    "dutch": "nld",
    "dutch, middle (ca. 1050-1350)": "dum",
    "dyula": "dyu",
    "dzongkha": "dzo",
    "eastern frisian": "frs",
    "edo": "bin",
    "efik": "efi",
    "egyptian (ancient)": "egy",
    "ekajuk": "eka",
    "elamite": "elx",
    "english": "eng",
    "english, middle (1100-1500)": "enm",
    "english, old (ca. 450-1100)": "ang",
    "erzya": "myv",
    "esperanto": "epo",
    "estonian": "est",
    "ewe": "ewe",
    "ewondo": "ewo",
    "fang": "fan",
    "fanti": "fat",
    "faroese": "fao",
    "fijian": "fij",
    "filipino": "fil",
    "finnish": "fin",
    "finno-ugrian languages": "fiu",
    "flemish": "nld",
    "fon": "fon",
    "french": "fra",
    "french, middle (ca. 1400-1600)": "frm",
    "french, old (842-ca. 1400)": "fro",
    "friulian": "fur",
    "fulah": "ful",
    "ga": "gaa",
    "gaelic": "gla",
    "galibi carib": "car",
    "galician": "glg",
    "ganda": "lug",
    "gayo": "gay",
    "gbaya": "gba",
    "geez": "gez",
    "georgian": "kat",
    "german": "deu",
    "german, low": "nds",
    "german, middle high (ca. 1050-1500)": "gmh",
    "german, old high (ca. 750-1050)": "goh",
    "germanic languages": "gem",
    "gikuyu": "kik",
    "gilbertese": "gil",
    "gondi": "gon",
    "gorontalo": "gor",
    "gothic": "got",
    "grebo": "grb",
    "greek, ancient (to 1453)": "grc",
    "greek, modern (1453-)": "ell",
    "greenlandic": "kal",
    "guarani": "grn",
    "gujarati": "guj",
    "gwich'in": "gwi",
    "haida": "hai",
    "haitian": "hat",
    "haitian creole": "hat",
    "hausa": "hau",
    "hawaiian": "haw",
    "hebrew": "heb",
    "herero": "her",
    "hiligaynon": "hil",
    "himachali languages": "him",
    "hindi": "hin",
    "hiri motu": "hmo",
    "hittite": "hit",
    "hmong": "hmn",
    "hungarian": "hun",
    "hupa": "hup",
    "iban": "iba",
    "icelandic": "isl",
    "ido": "ido",
    "igbo": "ibo",
    "ijo languages": "ijo",
    "iloko": "ilo",
    "imperial aramaic (700-300 bce)": "arc",
    "inari sami": "smn",
    "indic languages": "inc",
    "indo-european languages": "ine",
    "indonesian": "ind",
    "ingush": "inh",
    "interlingua (international auxiliary language association)": "ina",
    "interlingue": "ile",
    "inuktitut": "iku",
    "inupiaq": "ipk",
    "iranian languages": "ira",
    "irish": "gle",
    "irish, middle (900-1200)": "mga",
    "irish, old (to 900)": "sga",
    "iroquoian languages": "iro",
    "italian": "ita",
    "japanese": "jpn",
    "javanese": "jav",
    "jingpho": "kac",
    "judeo-arabic": "jrb",
    "judeo-persian": "jpr",
    "kabardian": "kbd",
    "kabyle": "kab",
    "kachin": "kac",
    "kalaallisut": "kal",
    "kalmyk": "xal",
    "kamba": "kam",
    "kannada": "kan",
    "kanuri": "kau",
    "kapampangan": "pam",
    "kara-kalpak": "kaa",
    "karachay-balkar": "krc",
    "karelian": "krl",
    "karen languages": "kar",
    "kashmiri": "kas",
    "kashubian": "csb",
    "kawi": "kaw",
    "kazakh": "kaz",
    "khasi": "kha",
    "khoisan languages": "khi",
    "khotanese": "kho",
    "kikuyu": "kik",
    "kimbundu": "kmb",
    "kinyarwanda": "kin",
    "kirdki": "zza",
    "kirghiz": "kir",
    "kirmanjki": "zza",
    "klingon": "tlh",
    "komi": "kom",
    "kongo": "kon",
    "konkani": "kok",
    "korean": "kor",
    "kosraean": "kos",
    "kpelle": "kpe",
    "kru languages": "kro",
    "kuanyama": "kua",
    "kumyk": "kum",
    "kurdish": "kur",
    "kurukh": "kru",
    "kutenai": "kut",
    "kwanyama": "kua",
    "kyrgyz": "kir",
    "ladino": "lad",
    "lahnda": "lah",
    "lamba": "lam",
    "land dayak languages": "day",
    "lao": "lao",
    "latin": "lat",
    "latin american spanish": "spa",
    "latvian": "lav",
    "leonese": "ast",
    "letzeburgesch": "ltz",
    "lezghian": "lez",
    "limburgan": "lim",
    "limburger": "lim",
    "limburgish": "lim",
    "lingala": "lin",
    "lithuanian": "lit",
    "lojban": "jbo",
    "low german": "nds",
    "low saxon": "nds",
    "lower sorbian": "dsb",
    "lozi": "loz",
    "luba-katanga": "lub",
    "luba-lulua": "lua",
    "luiseno": "lui",
    "lule sami": "smj",
    "lunda": "lun",
    "luo (kenya and tanzania)": "luo",
    "lushai": "lus",
    "luxembourgish": "ltz",
    "macedo-romanian": "rup",
    "macedonian": "mkd",
    "madurese": "mad",
    "magahi": "mag",
    "maithili": "mai",
    "makasar": "mak",
    "malagasy": "mlg",
    "malay": "msa",
    "malayalam": "mal",
    "maldivian": "div",
    "maltese": "mlt",
    "manchu": "mnc",
    "mandar": "mdr",
    "mandarin": "zho",
    "mandingo": "man",
    "manipuri": "mni",
    "manobo languages": "mno",
    "manx": "glv",
    "maori": "mri",
    "mapuche": "arn",
    "mapudungun": "arn",
    "marathi": "mar",
    "mari": "chm",
    "marshallese": "mah",
    "marwari": "mwr",
    "masai": "mas",
    "mayan languages": "myn",
    "mende": "men",
    "mi'kmaq": "mic",
    "micmac": "mic",
    "minangkabau": "min",
    "mirandese": "mwl",
    "mohawk": "moh",
    "moksha": "mdf",
    "moldavian": "ron",
    "moldovan": "ron",
    "mon-khmer languages": "mkh",
    "mong": "hmn",
    "mongo": "lol",
    "mongolian": "mon",
    "montenegrin": "cnr",
    "mossi": "mos",
    "multiple languages": "mul",
    "munda languages": "mun",
    "n'ko": "nqo",
    "nahuatl languages": "nah",
    "nauru": "nau",
    "navaho": "nav",
    "navajo": "nav",
    "ndebele, north": "nde",
    "ndebele, south": "nbl",
    "ndonga": "ndo",
    "neapolitan": "nap",
    "nepal bhasa": "new",
    "nepali": "nep",
    "newari": "new",
    "nias": "nia",
    "niger-kordofanian languages": "nic",
    "nilo-saharan languages": "ssa",
    "niuean": "niu",
    "no linguistic content": "zxx",
    "nogai": "nog",
    "norse, old": "non",
    "north american indian languages": "nai",
    "north ndebele": "nde",
    "northern frisian": "frr",
    "northern sami": "sme",
    "northern sotho": "nso",
    "norwegian": "nor",
    "norwegian bokmal": "nob",
    "norwegian bokmål": "nob",
    "norwegian nynorsk": "nno",
    "not applicable": "zxx",
    "nubian languages": "nub",
    "nuosu": "iii",
    "nyamwezi": "nym",
    "nyanja": "nya",
    "nyankole": "nyn",
    "nynorsk, norwegian": "nno",
    "nyoro": "nyo",
    "nzima": "nzi",
    "occidental": "ile",
    "occitan (post 1500)": "oci",
    "official aramaic (700-300 bce)": "arc",
    "oirat": "xal",
    "ojibwa": "oji",
    "old bulgarian": "chu",
    "old church slavonic": "chu",
    "old newari": "nwc",
    "old slavonic": "chu",
    "oriya": "ori",
    "oromo": "orm",
    "osage": "osa",
    "ossetian": "oss",
    "ossetic": "oss",
    "otomian languages": "oto",
    "pahlavi": "pal",
    "palauan": "pau",
    "pali": "pli",
    "pampanga": "pam",
    "pangasinan": "pag",
    "panjabi": "pan",
    "papiamento": "pap",
    "papuan languages": "paa",
    "pashto": "pus",
    "pedi": "nso",
    "persian": "fas",
    "persian, old (ca. 600-400 b.c.)": "peo",
    "philippine languages": "phi",
    "phoenician": "phn",
    "pilipino": "fil",
    "pohnpeian": "pon",
    "polish": "pol",
    "portuguese": "por",
    "portuguese (brazil)": "por",
    "prakrit languages": "pra",
    "provençal": "oci",
    "provençal, old (to 1500)": "pro",
    "punjabi": "pan",
    "pushto": "pus",
    "quechua": "que",
    "rajasthani": "raj",
    "rapanui": "rap",
    "rarotongan": "rar",
    "romance languages": "roa",
    "romanian": "ron",
    "romansh": "roh",
    "romany": "rom",
    "rundi": "run",
    "russian": "rus",
    "sakan": "kho",
    "salishan languages": "sal",
    "samaritan aramaic": "sam",
    "sami languages": "smi",
    "samoan": "smo",
    "sandawe": "sad",
    "sango": "sag",
    "sanskrit": "san",
    "santali": "sat",
    "sardinian": "srd",
    "sasak": "sas",
    "saxon, low": "nds",
    "scots": "sco",
    "scottish gaelic": "gla",
    "selkup": "sel",
    "semitic languages": "sem",
    "sepedi": "nso",
    "serbian": "srp",
    "serer": "srr",
    "shan": "shn",
    "shona": "sna",
    "sichuan yi": "iii",
    "sicilian": "scn",
    "sidamo": "sid",
    "sign languages": "sgn",
    "siksika": "bla",
    "sindhi": "snd",
    "sinhala": "sin",
    "sinhalese": "sin",
    "sino-tibetan languages": "sit",
    "siouan languages": "sio",
    "skolt sami": "sms",
    "slave (athapascan)": "den",
    "slavic languages": "sla",
    "slovak": "slk",
    "slovenian": "slv",
    "sogdian": "sog",
    "somali": "som",
    "songhai languages": "son",
    "soninke": "snk",
    "sorbian languages": "wen",
    "sotho, southern": "sot",
    "south american indian (other)": "sai",
    "south ndebele": "nbl",
    "southern altai": "alt",
    "southern sami": "sma",
    "spanish": "spa",
    "spanish (latino)": "spa",
    "sranan tongo": "srn",
    "standard moroccan tamazight": "zgh",
    "sukuma": "suk",
    "sumerian": "sux",
    "sundanese": "sun",
    "susu": "sus",
    "swahili": "swa",
    "swati": "ssw",
    "swedish": "swe",
    "swiss german": "gsw",
    "syriac": "syr",
    "tagalog": "tgl",
    "tahitian": "tah",
    "tai languages": "tai",
    "tajik": "tgk",
    "tamashek": "tmh",
    "tamil": "tam",
    "tatar": "tat",
    "telugu": "tel",
    "tereno": "ter",
    "tetum": "tet",
    "thai": "tha",
    "tibetan": "bod",
    "tigre": "tig",
    "tigrinya": "tir",
    "timne": "tem",
    "tiv": "tiv",
    "tlhingan-hol": "tlh",
    "tlingit": "tli",
    "tok pisin": "tpi",
    "tokelau": "tkl",
    "tonga (nyasa)": "tog",
    "tonga (tonga islands)": "ton",
    "tsimshian": "tsi",
    "tsonga": "tso",
    "tswana": "tsn",
    "tumbuka": "tum",
    "tupi languages": "tup",
    "turkish": "tur",
    "turkish, ottoman (1500-1928)": "ota",
    "turkmen": "tuk",
    "tuvalu": "tvl",
    "tuvinian": "tyv",
    "twi": "twi",
    "udmurt": "udm",
    "ugaritic": "uga",
    "uighur": "uig",
    "ukrainian": "ukr",
    "umbundu": "umb",
    "uncoded languages": "mis",
    "undetermined": "und",
    "upper sorbian": "hsb",
    "urdu": "urd",
    "uyghur": "uig",
    "uzbek": "uzb",
    "vai": "vai",
    "valencian": "cat",
    "venda": "ven",
    "vietnamese": "vie",
    "volapük": "vol",
    "votic": "vot",
    "wakashan languages": "wak",
    "walamo": "wal",
    "walloon": "wln",
    "waray": "war",
    "washo": "was",
    "welsh": "cym",
    "western frisian": "fry",
    "western pahari languages": "him",
    "wolof": "wol",
    "xhosa": "xho",
    "yakut": "sah",
    "yao": "yao",
    "yapese": "yap",
    "yiddish": "yid",
    "yoruba": "yor",
    "yupik languages": "ypk",
    "zande languages": "znd",
    "zapotec": "zap",
    "zaza": "zza",
    "zazaki": "zza",
    "zenaga": "zen",
    "zhuang": "zha",
    "zulu": "zul",
    "zuni": "zun",
}


def normalize_language(code: str) -> str:
    """Return the canonical ISO 639-2/T form of *code*.

    Handles surrounding whitespace, case, IETF/BCP 47 region suffixes
    (``de-DE``, ``pt_BR``), ISO 639-1 two-letter codes and ISO 639-2/B
    bibliographic codes. Unknown codes are returned lower-cased and
    stripped so they can still be matched literally (e.g. ``und``).
    """
    value = code.strip().lower()
    primary = value.replace("_", "-").split("-", 1)[0]
    if not primary:
        return value
    if len(primary) == 2:
        return ISO_639_1_TO_2T.get(primary, primary)
    return ISO_639_2B_TO_2T.get(primary, primary)


def language_from_name_or_code(value: str) -> str | None:
    """Return the ISO 639-2/T code for a language code *or* English name."""
    text = value.strip()
    if not text:
        return None
    lowered = text.lower()
    if lowered in ISO_639_NAMES:
        return ISO_639_NAMES[lowered]
    base = lowered.split("(", 1)[0].strip()
    if base in ISO_639_NAMES:
        return ISO_639_NAMES[base]
    code = normalize_language(text)
    if len(code) in (2, 3) and code.isalpha():
        return code
    return None


def known_languages() -> list[dict[str, str]]:
    """All languages as ``{"code", "name", "code1"}`` sorted by name.

    One entry per ISO 639-2/T code; the name is the first English name of
    the code in the table (e.g. ``deu`` → ``german``), title-cased.
    """
    two_letter = {v: k for k, v in ISO_639_1_TO_2T.items()}
    names: dict[str, str] = {}
    for name, code in ISO_639_NAMES.items():
        names.setdefault(code, name)
    return sorted(
        (
            {"code": code, "name": name.title(), "code1": two_letter.get(code, "")}
            for code, name in names.items()
        ),
        key=lambda entry: entry["name"],
    )
